// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver2.Data;

#nullable disable

namespace aspnetserver2.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220531165024_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("aspnetserver2.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apliciraj_link")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Iskustvo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naslov_oglasa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv_firme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slika_firme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Apliciraj_link = "Apliciraj_link 1",
                            Iskustvo = "Iskustvo 1",
                            Lokacija = "Lokacija 1",
                            Naslov_oglasa = "Post 1",
                            Naziv_firme = "Naziv_firme 1",
                            Opis = "",
                            Slika_firme = "Slika_firme 1"
                        },
                        new
                        {
                            PostId = 2,
                            Apliciraj_link = "Apliciraj_link 2",
                            Iskustvo = "Iskustvo 2",
                            Lokacija = "Lokacija 2",
                            Naslov_oglasa = "Post 2",
                            Naziv_firme = "Naziv_firme 2",
                            Opis = "",
                            Slika_firme = "Slika_firme 2"
                        },
                        new
                        {
                            PostId = 3,
                            Apliciraj_link = "Apliciraj_link 3",
                            Iskustvo = "Iskustvo 3",
                            Lokacija = "Lokacija 3",
                            Naslov_oglasa = "Post 3",
                            Naziv_firme = "Naziv_firme 3",
                            Opis = "",
                            Slika_firme = "Slika_firme 3"
                        },
                        new
                        {
                            PostId = 4,
                            Apliciraj_link = "Apliciraj_link 4",
                            Iskustvo = "Iskustvo 4",
                            Lokacija = "Lokacija 4",
                            Naslov_oglasa = "Post 4",
                            Naziv_firme = "Naziv_firme 4",
                            Opis = "",
                            Slika_firme = "Slika_firme 4"
                        },
                        new
                        {
                            PostId = 5,
                            Apliciraj_link = "Apliciraj_link 5",
                            Iskustvo = "Iskustvo 5",
                            Lokacija = "Lokacija 5",
                            Naslov_oglasa = "Post 5",
                            Naziv_firme = "Naziv_firme 5",
                            Opis = "",
                            Slika_firme = "Slika_firme 5"
                        },
                        new
                        {
                            PostId = 6,
                            Apliciraj_link = "Apliciraj_link 6",
                            Iskustvo = "Iskustvo 6",
                            Lokacija = "Lokacija 6",
                            Naslov_oglasa = "Post 6",
                            Naziv_firme = "Naziv_firme 6",
                            Opis = "",
                            Slika_firme = "Slika_firme 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
